[build]
  publish = "public"
  command = "hugo"

[context.production]
  command = "hugo"

  [context.production.environment]
    HUGO_VERSION = "v0.27"

[context.deploy-preview]
  command = "hugo --buildDrafts --buildFuture"
